app = 'coop'
primary_region = 'iad'

[build]

[env]
  PORT = '8080'
  HOST = '0.0.0.0'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 2500
    soft_limit = 2000

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
